@startuml
skinparam actorStyle awesome


usecase g1 as "Modifier infos client"
usecase g2 as "Créer un nouveau client"
usecase g3 as "Consulter un compte"
usecase g4 as "Créditer/Débiter un compte"
usecase g5 as "Créer un compte"
usecase g6 as "Effectuer un virement de compte à compte"
usecase g7 as "Clôturer un compte"

actor Guichetier

g1 -[hidden]-> g2
g2 -[hidden]-> g3
g3 -[hidden]-> g4
g4 -[hidden]-> g5
g5 -[hidden]-> g6
g6 -[hidden]-> g7

Guichetier -> g1
Guichetier -> g2
Guichetier -> g3
Guichetier -> g4
Guichetier -> g5
Guichetier -> g6
Guichetier -> g7


usecase c1 as "Rendre inactif un client"
usecase c2 as "Gérer les employés"

actor Chef

c1 -[hidden]-> c2

Chef -> c1
Chef -> c2


Chef --|> Guichetier
@enduml
