= Documentation technique V0 :
Thomas Falsimagne, Tilian Hure, Maxime Dourlent
v1.0, 2022-04-21

== I. Présentation de l'application :

=== 1. Use Case Global :

image::images/uc0.svg[]

[.text-justify]
Voici le Use Case Global de la V0 de l'application DailyBank.
Il y a deux types d'utilisateurs, les guichetiers et les chefs d'agence.
Selon que l'utilisateur soit guichetier ou chef d'agence, il a des droits d'administration qui sont différents.
[.text-justify]
Un guichetier peut modifier les informations d'un client, créer un nouveau client, consulter un compte et débiter un compte.
Un chef d'agence peut faire toutes ces actions et peut en plus rendre inactif un client.

=== II. Diagramme de classe des données global :

image::images/DC0.svg[]



== III. Architecture :

=== 1. Architecture générale

[.text-justify]
Pour l'application de la banque DailyBank, l'architecture générale est assez simple.
l'application est basée sur un fonctionnement centralisé, avec des postes de travails
qui sont directement reliés à une base de données.

[.text-justify]
Ces postes de travails sont les ordinateurs où travaillent les employés et les chefs d'agence.
Concernant la base de données, elle permet de stocker toutes les informations relatives à l'agence bancaire.
Que ce soit les informations des employés, des clients, des comptes et des opérations.

=== 2. Ressources externes :
==== 2.1. Librairies utilisées :

[.text-justify]
Au niveau des librairies, le code de l'application repose sur une seule librairie qui permet de lier l'application à la base de données. +
Cette librairie est : *objdbc6.jar*

==== 2.2 Exportation de l'application : 

[.text-justify]
L'application est généré en .jar, ce qui permet de lancer DailyBankApp sans
prérequis, simplement une JRE.

[.text-justify]
Il faut donc s'assurer que les postes de travail des employés possèdent une JRE 1.8 pour pouvoir faire fonctionner
le .jar sans encombre.

=== 3. Structuration de l'application :
[.text-justify]

==== 3.1 Pattern retenu pour la structuration du code : 

Le code de l'application est structuré en plusieurs packages.
Les packages Model, View, Controller et Tools.
[.text-justify]
Le principe qui nous a permis de structurer le code de cette manière est le MCV pattern.

[.text-justify]
Modèle-vue-contrôleur ou MVC est un motif d'architecture logiciel destiné aux interfaces graphiques lancé en 1978 et très populaire pour les applications web. Le motif est composé de trois types de modules ayant trois responsabilités différentes : les modèles, les vues et les contrôleurs.

==== 3.2 Aperçu de la structuration de DailyBankApp : 

[source]
----
├── application
    │   ├── control
    │   ├── tools
    │   └── view
    └── model
        ├── data
        └── orm
            └── exception
----

==== 3.2 Package Application : 

Le package application correspond à la partie View et la partie Controller avec ses deux packages "view" et "control" par rapport au pattern MVC.

. control -> Contient les fichiers permettant d'afficher les différentes fenêtres. 
. tools -> Contient les fichiers permettant de gérer certaines parties du code.
. view -> Contient les controllers des différentes fenêtres avec les fichiers fxml correspondants. 

==== 3.3 Package Model : 
Le package Model correspond à la partie Model du pattern MVC.

. data -> Package qui contient les fichiers représentant les personnes réelles et l'agence bancaire.
. orm -> Package qui contient les fichiers permettant la liaison à la base de données et
contient également le sous-package Exception contenant les fichiers java permettant de gérer les exceptions 

=== 4. Éléments essentiels :

==== 4.1 Prérequis pour le développeur :

[.text-justify]
Si le code de l'application devait être repris pour être amélioré ou modifié, le développeur devra avoir au préalable
une JRE version 1.8.
Il faudra ensuite qu'il ait pour environnement de développement le logiciel Eclipse.
Il devra également avoir un Workspace configuré en JavaFX avec le logiciel SceneBuilder intégré dans le buildpath.

== IV. Description et explication des fonctionnalités implémentées :

=== 1. Guichetier

==== 1.1 Modifier info client :

le guichetier peut modifier les informations du client. Il peut donc modifier le nom du client, son adresse, etc.

===== Use case correspondant :
image::images/modifierInfo.svg[]


==== 1.2 Créer un client :

Il est également possible pour lui de créer un nouveau client.

===== Use case correspondant :
image::images/creerClient.svg[]



==== 1.3 Consulter un compte :

Le guichetier peut également consulter un compte.

===== Use case correspondant :

image::images/consulterCompte.svg[]


==== 1.4 Débiter un compte :

Il peut débiter un compte

===== Use case correspondant :
image::images/debiterCompte.svg[]
